use std::path::Path;
use std::fs;
use std::io::Read;
use crate::config::{ClassifierConfig, ClassAction};

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize)]
pub enum FileClass {
    Generated,
    Vendored,
}

#[derive(Debug, Clone)]
pub struct Classification {
    pub class: FileClass,
    pub action: ClassAction,
    /// Source of the match: "path", "header", "gitattributes", "config"
    pub reason: &'static str,
    /// The specific pattern or marker that triggered the match
    pub pattern: String,
}

// ── Built-in generated path patterns ─────────────────────────────────────────

/// Directory prefixes that indicate generated output.
const GEN_DIR_PREFIXES: &[&str] = &[
    "dist/", "build/", "out/", "output/", "_build/", "_site/",
    "__pycache__/", ".cache/", ".next/", ".nuxt/", ".svelte-kit/",
    ".output/", ".vite/", ".nyc_output/",
];

/// Exact file names that are always generated (lock files, sum files, etc.).
const GEN_EXACT_NAMES: &[&str] = &[
    "Cargo.lock", "package-lock.json", "yarn.lock", "pnpm-lock.yaml",
    "poetry.lock", "Gemfile.lock", "go.sum", "composer.lock",
    "Pipfile.lock", "pdm.lock", "uv.lock", "flake.lock",
];

/// File path suffixes (applied to the full relative path).
const GEN_PATH_SUFFIXES: &[&str] = &[
    ".min.js", ".min.css", ".min.ts", ".bundle.js", ".chunk.js",
    ".pb.go", ".pb.cc", ".pb.h", ".pb.swift", ".pb.kt",
    ".g.dart", ".freezed.dart", ".gr.dart",
    ".generated.ts", ".generated.js", ".generated.cs",
    ".generated.dart", ".generated.go", ".gen.go", ".gen.ts",
    ".ambr",
];

/// Substrings within the filename (not full path) that indicate codegen.
const GEN_FILENAME_CONTAINS: &[&str] = &[
    "_pb2.py", "_pb2_grpc.py", "_grpc.pb.go",
];

// ── Built-in vendored path patterns ──────────────────────────────────────────

const VENDOR_DIR_PREFIXES: &[&str] = &[
    "vendor/", "third_party/", "third-party/", "_vendor/",
    "extern/", "external/", "deps/",
    "node_modules/", "bower_components/",
    "Pods/", "Carthage/Checkouts/",
];

// ── Header markers indicating a generated file ────────────────────────────────

const GENERATED_HEADER_MARKERS: &[&str] = &[
    "@generated",
    "do not edit",
    "code generated by",
    "autogenerated",
    "auto-generated",
    "this file is automatically generated",
    "generated by protoc",
    "generated by the protocol buffer compiler",
    "<auto-generated>",
    "# this file is generated",
    "// generated by",
    "/* generated",
];

// ─────────────────────────────────────────────────────────────────────────────

pub struct FileClassifier {
    config: ClassifierConfig,
    /// Patterns from .gitattributes with linguist-generated
    gitattr_generated: Vec<String>,
    /// Patterns from .gitattributes with linguist-vendored
    gitattr_vendored: Vec<String>,
}

impl FileClassifier {
    pub fn new(config: ClassifierConfig, repo_root: &Path) -> Self {
        let (gitattr_generated, gitattr_vendored) = Self::parse_gitattributes(repo_root);
        Self { config, gitattr_generated, gitattr_vendored }
    }

    fn parse_gitattributes(repo_root: &Path) -> (Vec<String>, Vec<String>) {
        let attr_path = repo_root.join(".gitattributes");
        let mut generated = Vec::new();
        let mut vendored = Vec::new();

        let Ok(content) = fs::read_to_string(&attr_path) else {
            return (generated, vendored);
        };

        for line in content.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            // Format: <pattern> [attr=value ...]
            // Attributes may be tab- or space-separated from the pattern.
            let mut parts = line.splitn(2, |c: char| c == ' ' || c == '\t');
            let pattern = match parts.next() {
                Some(p) => p,
                None => continue,
            };
            let attrs = parts.next().unwrap_or("");
            if attrs.contains("linguist-generated") {
                generated.push(pattern.to_string());
            } else if attrs.contains("linguist-vendored") {
                vendored.push(pattern.to_string());
            }
        }
        (generated, vendored)
    }

    /// Returns the first classification that matches, or `None` for original files.
    /// Detection order: gitattributes → path patterns → header scan.
    pub fn classify(&self, relative_path: &str, content_head: &[u8]) -> Option<Classification> {
        let filename = Path::new(relative_path)
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("");

        // 1. .gitattributes (linguist-generated / linguist-vendored)
        for pat in &self.gitattr_generated {
            if gitignore_match(relative_path, pat) {
                return Some(Classification {
                    class: FileClass::Generated,
                    action: self.config.generated_action,
                    reason: "gitattributes",
                    pattern: pat.clone(),
                });
            }
        }
        for pat in &self.gitattr_vendored {
            if gitignore_match(relative_path, pat) {
                return Some(Classification {
                    class: FileClass::Vendored,
                    action: self.config.vendored_action,
                    reason: "gitattributes",
                    pattern: pat.clone(),
                });
            }
        }

        // 2. Path patterns (built-ins, then config extras)
        if let Some(cls) = self.check_path_patterns(relative_path, filename) {
            return Some(cls);
        }

        // 3. Header scan
        if let Some(cls) = self.check_header(content_head) {
            return Some(cls);
        }

        None
    }

    fn check_path_patterns(&self, relative_path: &str, filename: &str) -> Option<Classification> {
        let suppressed = |p: &str| self.config.suppress.iter().any(|s| s == p);

        // Generated: directory prefixes
        for &pat in GEN_DIR_PREFIXES {
            if !suppressed(pat) && path_has_dir_prefix(relative_path, pat) {
                return Some(self.gen_path(pat));
            }
        }

        // Generated: exact file names
        for &name in GEN_EXACT_NAMES {
            if !suppressed(name) && filename == name {
                return Some(self.gen_path(name));
            }
        }

        // Generated: path suffixes
        for &suf in GEN_PATH_SUFFIXES {
            if !suppressed(suf) && relative_path.ends_with(suf) {
                return Some(self.gen_path(suf));
            }
        }

        // Generated: filename substrings
        for &sub in GEN_FILENAME_CONTAINS {
            if !suppressed(sub) && filename.contains(sub) {
                return Some(self.gen_path(sub));
            }
        }

        // Vendored: directory prefixes
        for &pat in VENDOR_DIR_PREFIXES {
            if !suppressed(pat) && path_has_dir_prefix(relative_path, pat) {
                return Some(self.vendor_path(pat));
            }
        }

        // Config-defined extra generated patterns
        for pat in &self.config.generated {
            if path_has_dir_prefix(relative_path, pat) || relative_path.ends_with(pat.as_str()) {
                return Some(Classification {
                    class: FileClass::Generated,
                    action: self.config.generated_action,
                    reason: "config",
                    pattern: pat.clone(),
                });
            }
        }

        // Config-defined extra vendored patterns
        for pat in &self.config.vendored {
            if path_has_dir_prefix(relative_path, pat) || relative_path.ends_with(pat.as_str()) {
                return Some(Classification {
                    class: FileClass::Vendored,
                    action: self.config.vendored_action,
                    reason: "config",
                    pattern: pat.clone(),
                });
            }
        }

        None
    }

    fn check_header(&self, content_head: &[u8]) -> Option<Classification> {
        let head = extract_head(content_head);
        let lower = head.to_ascii_lowercase();
        for &marker in GENERATED_HEADER_MARKERS {
            if lower.contains(marker) {
                return Some(Classification {
                    class: FileClass::Generated,
                    action: self.config.generated_action,
                    reason: "header",
                    pattern: marker.to_string(),
                });
            }
        }
        None
    }

    fn gen_path(&self, pat: &str) -> Classification {
        Classification {
            class: FileClass::Generated,
            action: self.config.generated_action,
            reason: "path",
            pattern: pat.to_string(),
        }
    }

    fn vendor_path(&self, pat: &str) -> Classification {
        Classification {
            class: FileClass::Vendored,
            action: self.config.vendored_action,
            reason: "path",
            pattern: pat.to_string(),
        }
    }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/// True if `relative_path` starts with `dir` (e.g. "vendor/") or contains
/// a path component that starts the segment (e.g. "src/vendor/foo").
fn path_has_dir_prefix(relative_path: &str, dir: &str) -> bool {
    relative_path.starts_with(dir)
        || relative_path.contains(&format!("/{dir}"))
}

/// Extract up to 5 newlines or 512 bytes of content, whichever limit is hit first.
fn extract_head(content: &[u8]) -> String {
    let cap = content.len().min(512);
    let chunk = &content[..cap];
    let mut newlines = 0usize;
    let mut end = cap;
    for (i, &b) in chunk.iter().enumerate() {
        if b == b'\n' {
            newlines += 1;
            if newlines >= 5 {
                end = i + 1;
                break;
            }
        }
    }
    String::from_utf8_lossy(&chunk[..end]).into_owned()
}

/// Use the `ignore` crate's gitignore matcher so patterns from .gitattributes
/// support the same glob syntax git uses.
fn gitignore_match(path: &str, pattern: &str) -> bool {
    let mut builder = ignore::gitignore::GitignoreBuilder::new(".");
    let _ = builder.add_line(None, pattern);
    builder.build().map_or(false, |gi| gi.matched(path, false).is_ignore())
}

/// Read at most `max_bytes` from a file without loading it entirely.
pub fn read_head_bytes(path: &Path, max_bytes: usize) -> Vec<u8> {
    let mut buf = vec![0u8; max_bytes];
    match fs::File::open(path) {
        Ok(mut f) => {
            let n = f.read(&mut buf).unwrap_or(0);
            buf.truncate(n);
            buf
        }
        Err(_) => Vec::new(),
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::ClassifierConfig;

    fn classifier() -> FileClassifier {
        FileClassifier::new(ClassifierConfig::default(), Path::new("."))
    }

    #[test]
    fn vendor_dir_prefix() {
        let c = classifier().classify("vendor/foo/bar.rs", &[]);
        assert!(matches!(c.map(|x| x.class), Some(FileClass::Vendored)));
    }

    #[test]
    fn nested_vendor() {
        let c = classifier().classify("src/vendor/lib.js", &[]);
        assert!(matches!(c.map(|x| x.class), Some(FileClass::Vendored)));
    }

    #[test]
    fn lock_file() {
        let c = classifier().classify("Cargo.lock", &[]);
        assert!(matches!(c.map(|x| x.class), Some(FileClass::Generated)));
    }

    #[test]
    fn minified_js() {
        let c = classifier().classify("static/app.min.js", &[]);
        assert!(matches!(c.map(|x| x.class), Some(FileClass::Generated)));
    }

    #[test]
    fn proto_generated_py() {
        let c = classifier().classify("proto/foo_pb2.py", &[]);
        assert!(matches!(c.map(|x| x.class), Some(FileClass::Generated)));
    }

    #[test]
    fn header_do_not_edit() {
        let head = b"// Code generated by protoc-gen-go. DO NOT EDIT.\npackage foo\n";
        let c = classifier().classify("internal/foo.go", head);
        assert!(matches!(c.map(|x| x.class), Some(FileClass::Generated)));
    }

    #[test]
    fn header_at_generated() {
        let head = b"// @generated\n// by some tool\n";
        let c = classifier().classify("src/schema.ts", head);
        assert!(matches!(c.map(|x| x.class), Some(FileClass::Generated)));
    }

    #[test]
    fn header_scan_limited_to_5_lines() {
        // Marker on line 6 should NOT be detected
        let head = b"line1\nline2\nline3\nline4\nline5\n// DO NOT EDIT\nmore stuff";
        let c = classifier().classify("src/something.ts", head);
        assert!(c.is_none(), "marker on line 6 should be past the scan window");
    }

    #[test]
    fn original_file_unclassified() {
        let c = classifier().classify("src/main.rs", b"fn main() {}");
        assert!(c.is_none());
    }

    #[test]
    fn suppress_overrides_builtin() {
        let mut cfg = ClassifierConfig::default();
        cfg.suppress.push("vendor/".to_string());
        let clf = FileClassifier::new(cfg, Path::new("."));
        let c = clf.classify("vendor/foo.rs", &[]);
        assert!(c.is_none(), "suppressed pattern should not match");
    }

    #[test]
    fn config_extra_generated() {
        let mut cfg = ClassifierConfig::default();
        cfg.generated.push("gen/".to_string());
        let clf = FileClassifier::new(cfg, Path::new("."));
        let c = clf.classify("gen/schema.rs", &[]);
        assert!(matches!(c.map(|x| x.class), Some(FileClass::Generated)));
    }
}
